name: Makefile CI

on:
  push:
    branches: [ workspace/group-2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make bootstrap
      
    - name: Run tests and CI build
      run: make cibuild
